### ISSUE TITLE
Subdomain Takeover

### ISSUE THREAD

**Issue by JoeMilian** [qooxdoo/qooxdoo.github.io#1]
Hey,

I noticed you had an unclaimed GitHub page, I took it over so no attacker is able to use it.

The subdomain: http://manual.qooxdoo.org

I hope I have informed you enough, If there are any issues please don't hesitate to message me.

Kind regards,

Joe (https://twitter.com/JoeMilian1)

**Comment by oetiker** [comment]
oops ... having a * cname is probably not such a good idea ... fixed ... thanks.
